Added support for trusted CA specification through 'ca-pins' parameter
teleport-actions/root pull request #39
Opened 2023-07-26 18:26 UTC by w4

2023-07-31 09:09 UTC, strideynet requested changes
Looks good ! Just one suggested change on the description so people know these aren't necessary in most cases.

2023-07-31 09:09 UTC, strideynet commented on common/action.yml
> +    description: 'Specifies one or more trusted CAs'
```suggestion
    description: 'Specifies one or more trusted CAs to bootstrap initial trust when connecting directly to an Auth Server. This is not required for Teleport Cloud or when connecting via a Teleport Proxy.'
```

2023-07-31 22:14 UTC, w4 commented on common/action.yml
> +    description: 'Specifies one or more trusted CAs'
updated, thanks!

2023-08-01 08:26 UTC, strideynet approved these changes

2023-08-01 08:31 UTC, merged